version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      liveorder_network:
        ipv4_address: ${POSTGRES_IP}

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      liveorder_network:
        ipv4_address: ${REDIS_IP}

networks:
  liveorder_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
